### ISSUE TITLE
Corrections to existing grades

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#1]
We need to add an option for teachers to submit corrections to existing grades. 

Some thoughts on the UX for corrections: say that you have submitted a final grade (partially), so that when you open the grading screen there is now a retake column. What you want to do is correct some or all of the submitted final grades, and the option to require a reason is enabled. A possible way this might work:
- By default all submitted grades are locked
- You click a 'correct final grade' button somewhere (not for a specific grade, but for the entire column)
- Now the grades that you have already submitted become 'editable' (in terms of the data model you are actually creating one or more new lists with new entries, but this is the UX) and all other cells (any final grades you have not yet submitted and the retake) become uneditable. You can calculate, upload or manually enter grades.
- When submitting, you are asked for a reason (instead of an exam date, which will be the same as the original one) and you sign the grade
- After submission the new grades are shown and are again locked
- Corrected grades show a CORRECTED indicator, with a mouseover showing the original grade

**Planning**
Live in semester 2.

**Comment by goomens** [comment]
The way this is currently implemented with the extra column is slightly different than what was suggested here, but I think it should work. One thing that came up during the demo is that it would be good to have a 'plus' button like in the retake column before you can add a corrected grade (which is only there if an original grade exists, of course) rather than showing a text box for every student.

**Comment by goomens** [comment]
One other addition: if the corrections concerns a list that has been submitted more than 6 weeks ago, it should not be processed to SIS automatically but needs to be manually approved by the education desk. It should be signed normally, but then `CorrectionDate` should not be set (at least, I think that's the easiest way to do this).

**Comment by rvankoten** [comment]
Working version is up on ACC

Some small todo's:
- [x] add 'exit correction mode' button
- [x] original grade tooltip
- [x] plus icon for corrections
- [x] remark input field
- [x] do not process when submitted longer than 6 weeks ago
- [x] <del>optionally: history dialog</del>
- [x] <del>fix corrections in other tasks (mainly sistasks)</del>

**Comment by goomens** [comment]
This history looks good like this, but it doesn't show all the details; if it's clickable with a small popup that shows the reason and submission date of the correction (or multiple corrections), I think we're there.

**Comment by rvankoten** [comment]
The usage of the new correction target field on the entries will be checked in issue #75

**Comment by rvankoten** [comment]
Addition of the history dialog is moved to issue #76
