### ISSUE TITLE
Publish/submit button titles

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#107]
### Component
Main grading screen

### Summary
- [ ] The title of the button "Publish Calculated Grades" will change into "Publish Grade Calculation, if edits and additions are made to the calculation, the title of the button will change to "Republish Grade Calculation". 
- [x] In addition, when grades are first calculated the button "Recalculate Grades" will be named "Calculate Grades" and when settings are changed, this button will be replaced with "Recalculate Grades" as to prevent any confusion.
- [x] Furthermore, in the submit dialog. There will also be an additional checkbox where teachers can decide not only submit the calculation, but also publish it at the same time, this checkbox will be off by default to prevent teachers from incorrectly submitting grades if they are not sure of their calculation.

### Reported by
FMG (Bart)

**Comment by goomens** [comment]
FMG also wants to make the 'publish' option more prominent. How can we solve that? Publish checkbox in submit screen?

**Comment by goomens** [comment]
Some options, not mutually exclusive:
1. Rename 'Submit grades' to 'Submit final grades'
2. Once a grade calculation has been set up, move the 'publish calculated grades' button out of the grade calculation menu and rename it 'publish grade calculation' (where the publish dialog makes it clear that grades are published as well)
3. In the submit dialog, if a grade calculation has been set up, show a checkbox to publish the grade calculation in addition to submitting

**Comment by goomens** [comment]
See discussion [here](https://amsuni-my.sharepoint.com/:w:/g/personal/a_c_vierveijzer_uva_nl/EdVugkOMLNdIlkLijWfboUoBbn1_73pVScqspjywEwg08Q?rtime=H_xxtcnO2Ug), consensus still pending 😄 .

**Comment by DJGvanBeeren** [comment]
@goomens as you know, consensus has been reached! I have edited the main main comment to reflect the choices that we have come to a consensus to!

**Comment by goomens** [comment]
For the third point, I added a link to the publish dialog instead of a checkbox.
