### ISSUE TITLE
Show examiners per group

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#110]
### Component
Main grade screen

### Summary
Add an option to see an overview of examiners assigned per group. Follow up to #39 

### Reported by
FGw (Joris)

**Comment by goomens** [comment]
Possible solution: we make the 'you are not an examiner for this student' icon clickable, opening a dialog that shows all groups and examiners (similar to the one in the grading overview).

**Comment by jvdberge** [comment]
The suggested solution would not be sufficient. The "You are not an examiner" icon is only shown for users who are examiner for at least one workgroup. They can already see more info on the examiner for that student by trying to submit: "This list can only be signed by one of the examiners: a, b, c". 
Our concern here lies mainly with everyone (LFB, OA, teachers, coordinator) who has no examiner rights (and no active Submit button) in the course, but needs information about the (other) examiners. 
Maybe a menu entry "Course details"? This could also hold info on Title, ECs, ...?

**Comment by goomens** [comment]
Since there doesn't seem to an obvious menu where this should go, I've added an i-icon:
![Screenshot 2022-01-03 at 15 55 02](https://user-images.githubusercontent.com/5849619/147945222-667918e8-5a5a-4a77-9ca2-c9f2f1299d83.png)

**Comment by jvdberge** [comment]
I agree about the menu item. An i-icon seems to do the trick, but will this icon then also be visible when there are no workgroups (when there is no dropdown filter box)? The main issue is not associated with workgroups, but the solution seems to go that way?

Another possible location might be in the area of the submit button, and outside of the student list area. There is more "general info" there already (exam date, grading scheme, ...). But we might run into problems with the Question-mark-icon there. Maybe something can be done about the style or arrangement of the icons (grey?). Did the style guide of mbstudio give any additional icons?

**Comment by goomens** [comment]
Ah yes, I assumed it was mostly relevant for courses with groups. Of course we can still show the icon in the same place if there is no group dropdown, but it will be less intuitive what info it refers to. Showing it somewhere around the submit button seems logical as well (as a grey info icon maybe), but there is no immediately obvious place to put it there either.

**Comment by jvdberge** [comment]
I think the examiner info would best be placed on the right side. Maybe we can fit it below the grading scheme in this way (with small or moderate line spacing):
> Valid grades: Numeric, NAV, NAP
> EC: 6
> Examiners: (i)    

where (i) is a grey (same as the text) i-icon with tooltip: "click here" (e.g. from [here](https://www.iconsdb.com/custom-color/info-icons.html), custom color #585858), or, alternatively, just the text "click here"?
And maybe the dialog could also show the non-graded student count?

**Comment by goomens** [comment]
I've moved the info icon there (we can still play around with spacing and colors). I've left out the EC for now to limit the space used as much as possible (as there is already a need to scroll the bar on small screens), but the EC is in the info dialog as well
