### ISSUE TITLE
BSA flag in reminder mails

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#124]
### Component
Reminder mails

### Summary
Enable and document the BSA flag that allows reminders for BSA-sensitive courses to be customised, so that it can be used by all faculties.

### Reported by
FMG (Angela)

**Comment by DJGvanBeeren** [comment]
@goomens in extension to this, a request came to my attention that it perhaps is also fruitful (from IIS side) to be able to set reminder emails not only per programme, but also per course in each programma. :-) would that be possible.
