### ISSUE TITLE
Easier sorting/filtering pending grades

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#125]
### Component
Mail grade screen

### Summary
Currently when sorting a (retake) grade column, pending grades with empty boxes and cells where the plus icon is shown are treated the same. Change this so that when sorting they are treated separately and/or make it possible to filter the view.

### Reported by
FMG (Laura)

**Comment by jvdberge** [comment]
Also, enable sorting or filtering on status-column (green ticks, unsigned, waiting, error, ...) [added by Gerrit when opening #128 (see Teams)]
