### ISSUE TITLE
Make partial calculations possible without partial grading enabled

### ISSUE THREAD

**Issue by DJGvanBeeren** [UvA-FNWI/GradeTool#127]
### Component
Grade calculation

### Summary

For certain courses in PSY, partial grading has been disabled, but not all grades should be calculated at the same time. Can we separate the two to make it possible to do partial calculations even when partial booking is disabled?

### Reported by
FMG-PSY (Laura)

Further context can be found in the following helpscout topic:
https://secure.helpscout.net/conversation/1760227805/94702?folderId=4804577

**Comment by goomens** [comment]
Current implementation: the 'recalculate selected' button is always available and adds checkboxes when they are not present.
