### ISSUE TITLE
Improve grade screen layout

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#128]
### Component
Main grading screen

### Summary
Currently the screen can be very cluttered, in particular with partial grading enabled. Some suggestions to improve it:
- Do not show text boxes for submitted grades
- Remove lock icons
- Do not show 'EDITED' when grade calculation is not used

### Reported by
FGw (Joris)

**Comment by jvdberge** [comment]
Proposal and considerations(!) in Teams (in Dutch):

https://teams.microsoft.com/l/message/19:c189791914bf401794df907b751fece1@thread.tacv2/1643646278405?tenantId=a0f1cacd-618c-4403-b945-76fb3d6874e5&groupId=b96c398c-fea4-40c7-976e-b512879e106c&parentMessageId=1643646278405&teamName=Implementatie%20Cijferregistratieapplicatie&channelName=General&createdTime=1643646278405

[Sorting or filtering on status-column (green ticks, unsigned, waiting, error, ...) has been moved to issue #125 ]

Current situation and mock-up proposal (explanation in Teams): 
![Current Grade screen layout](https://user-images.githubusercontent.com/86349459/161037449-2beb14db-d5c9-4888-9ff7-6dc085655b82.png)

![Proposed Grade screen layout](https://user-images.githubusercontent.com/86349459/161037484-6fd94099-6878-47f3-b124-60977c4e8088.png)

**Comment by jvdberge** [comment]
The disabled checkbox is not available on your server:
`https://acc.datanose.nl/Images/canvas_checkbox-disabled.png`
gives a 404.

**Comment by goomens** [comment]
Not sure what went wrong there. Should be fixed now!
