### ISSUE TITLE
Examiner has to enter grades for rejected students

### ISSUE THREAD

**Issue by DJGvanBeeren** [UvA-FNWI/GradeTool#130]
### Component
Grade submission screen
### Summary
When an examiner has manually added students but they have been rejected by the administration, retake grades must still be entered if they didn't have a passing grade.
### Steps to reproduce
- Add a student to a course and submit an insufficient grade
- As admin, reject the grade
- Return to the grading screen and try to submit retake grades
### Reported by
Damian/Reinout in: https://secure.helpscout.net/conversation/1767466030/95178?folderId=4804577

**Comment by goomens** [comment]
No longer relevant since we filter out rejected grades
