### ISSUE TITLE
Confusing error when submitting retake grades

### ISSUE THREAD

**Issue by DJGvanBeeren** [UvA-FNWI/GradeTool#132]
### Component
Grade Entry

### Summary
When teachers and the like have to enter grades for the first time, they run into the following error message:

This can understandably confuse professors/teachers, as they then incorrectly assume that the pop-up means that things have gone wrong with the entry of grades. **The solution therefore is not showing this message when the 1st attempt hasn't been entered into SIS yet.**

### Reported by
Laura van Aalst

### Link to Helpscout issue for reference/email:
https://secure.helpscout.net/conversation/1804898827/98105/

**Comment by goomens** [comment]
@DJGvanBeeren Please clarify this issue with reproduction steps. When exactly does the error occur?

**Comment by c-wegman** [comment]
The confusing error message:
![Picture1](https://user-images.githubusercontent.com/78905856/179731367-246440e5-b50a-41ad-8557-6248eea96033.png)

This seems to happen when the grades of the 1st attempt are not yet visible in SIS and the teacher wants to submit the grades of the 2nd attempt (herkansing).

**Comment by goomens** [comment]
Issue does not appear to reproduce anymore, possibly because of earlier changes to retake submission conditions
