### ISSUE TITLE
Show remarks in grading overview

### ISSUE THREAD

**Issue by DJGvanBeeren** [UvA-FNWI/GradeTool#133]
### Component
Grading overview

### Summary
 
Can we implement the 'remark' field as show below on datanose.nl/#gradelists
![gradelist_wanted](https://user-images.githubusercontent.com/87482215/157415409-16dfc85d-8f9a-4361-ae44-b934bef47c5b.png)
on the page datanose.nl/#examdates seen below and place the 'remark' field on the very right of the page to keep it consistent across both pages?

![2022-03-09 10_11_02-Grading overview](https://user-images.githubusercontent.com/87482215/157410456-86d897f3-63ab-4453-ba6e-a098fcc83479.png)

### Reported by
FMG (Angela and Eefje)

**Comment by goomens** [comment]
One page is per list, the other is per course, so we have to think about what remark we show and how. Basic option would be to show the remarks for all lists here
