### ISSUE TITLE
[User Rights] Enable ICTO Cijferbeheerders to see who the examinators are for grades

### ISSUE THREAD

**Issue by DJGvanBeeren** [UvA-FNWI/GradeTool#134]
### Component
Gradelists

### Summary

Currently ICTO's don't have the right to see who the examinor for a course/grade is, which brings an interesting problem. In some cases the professor/teacher that they are trying to help simply does not have the rights to submit the grades they are trying to enter.

**To mitigate this, Madelon Schuur has suggested we make it visible who the examinor is for the course.** 

**So we would go from this situation:**

![1](https://user-images.githubusercontent.com/87482215/157415025-78a69f46-4acf-4362-afda-d913b31ff2ab.png)

**To this:**

![2](https://user-images.githubusercontent.com/87482215/157414884-378a41aa-a1a2-4b6b-9479-931948b5f6ab.png)

### Reported by

Madelon Schuur via email.

**Comment by DJGvanBeeren** [comment]
This will help with increasing the speed with which we can help professors. So want to put this on the priority list :-) @goomens

**Comment by goomens** [comment]
This is already visible, I think? Click the i icon after 'examiners' in the right bar

**Comment by goomens** [comment]
@DJGvanBeeren
