### ISSUE TITLE
[Bug/Enhancement] Make the retake column stay whenever an assignment has been coupled.

### ISSUE THREAD

**Issue by DJGvanBeeren** [UvA-FNWI/GradeTool#135]
### Component
Grading/Retake

### Summary
Blijkbaar stonden er op de achtergrond nog herkansingsassignments gekoppeld aan de tool terwijl er in de Herkansing-drop-down 'Geen herkansing' geselecteerd was. Het was dus niet zichtbaar voor ons dat deze herkansingsassignments gekoppeld waren. Eerder is het drop-down menu dus blijkbaar op 'Deelresultaten kunnen apart herkanst worden' gezet en zijn er in de herkansingskolom assignments gekoppeld.

Is het misschien mogelijk om de Herkansing kolom (die verschijnt bij de selectie van 'Deelresultaten kunnen apart herkanst worden') in de cijferberekening niet te laten verdwijnen wanneer er iets gekoppeld is in die kolom en je dan een andere optie selecteert in de Herkansing-drop-down (zoals bijv. de optie 'Geen herkansing'?

### Reported by
Laura van Aalst

**Comment by goomens** [comment]
@DJGvanBeeren For bugs, please include reproduction steps. I tried to reproduce this but I don't seem to be able to
