### ISSUE TITLE
Verify session start/end date checks

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#14]
Make sure that when processing results to SIS, the exam date is correctly checked against the start/end dates of the session. Do not try to process grades that do not fall within the session.

See DEF881 and DEF1192.

**Comment by goomens** [comment]
This doesn't quite seem to work yet, Joris says (in DEF1192):
> Helaas geen succes bij Hertest:Cijfer AVV in zelfde vak (123000002Y, in S12) toegevoegd voor 12604437. Geprobeerd door te zetten vandaag, 12-10. S12 begint op 26-10.De Submit-knop was niet disabled.Na 2FA en herladen staat het cijfer op groen vinkje: Processed.Het cijfer is ook doorgezet naar SIS en geboekt met beoordelingsdatum 12-10-2020 in act. 8997, de S12-act. waar student in stond.

**Comment by rvankoten** [comment]
Well that's because acc wasn't updated and I never intended to disable the button.
Do we really want to hide the button outside the session?

**Comment by goomens** [comment]
No, we don't need to hide the button, but the connector should give an error rather than process the grade. If that's already there then it suffices to update acc and ask them to test again I think :-).
