### ISSUE TITLE
Add submission not allowed icon

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#16]
If 
1. the user is allowed to book grades for some students, but
2. not all of them
show an icon for the students they aren't allowed to submit grades for.

DEF907

**Comment by goomens** [comment]
This looks good, but if I look at e.g. https://acc.datanose.nl/#course[82364]/canvasgrading then I see the icon for all students since I am not allowed to submit any grades. Maybe in this case don't show the icon, but instead grey out the submission button with a mouseover ("You cannot submit grades since you aren't an examiner for this course"/"U kunt geen cijfers inleveren omdat u geen examinator voor dit vak bent.")

**Comment by rvankoten** [comment]
Done, but adding a disabled attribute to a button was a bit complicated.
Current solution replaces button by a div that looks like a disabled button -> not a desired solution
