### ISSUE TITLE
(Dutch) language label fixes

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#18]
When looking at the Dutch language version I see a few minor inconsistencies:
- [x] "All students" in the group dropdown lacks a translation
- [x] For non-FNWI courses the single person field should be 'Assessor'/'Beoordelaar'
- [x] The groups are shown as "Section Group X" (for an FNWI course), which seems a bit superfluous :-)
- [x] "Inlever datum" should be "Tentamendatum"/"Exam date"
- [x] The date picker for the exam date lacks a Dutch translation
- [x] "EDITED" should be "BEWERKT"

**Comment by rvankoten** [comment]
All done

**Comment by goomens** [comment]
I still see "EDITED"!

**Comment by rvankoten** [comment]
Ah, I missed the default EDITED text. Only tested the ones that update when changing grades
