### ISSUE TITLE
Grade error icon layout issue

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#19]
When expanding a row with an invalid grade the error icon shifts to an odd spot:
![Screen Shot 2020-09-12 at 17 36 37](https://user-images.githubusercontent.com/5849619/92999108-aee09800-f51e-11ea-8e0a-062ece3f81d8.png)

**Comment by rvankoten** [comment]
Also the button row doesn't have the correct number of table cells (barely visible in the image at the bottom right)

**Comment by rvankoten** [comment]
Fixed
