### ISSUE TITLE
PDF upload requirement

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#21]
Certain FNWI programmes have a requirement that a PDF version of the examination is uploaded before grade submission. This check is currently still present in Canvas layout, but there is no option to upload the PDF. Add that option in the submission dialog.

**Comment by rvankoten** [comment]
Added, needed a bit more changes because of the way the canvas version handles all lists at once.
Still don't like the layout of the checkbox and exams table in the submission dialog.
Not sure how to make it better.

**Comment by goomens** [comment]
Layout is good enough, I think. But it seems that while uploading the exam is now possible, the check is no longer there? At least, I was able to submit a list [here](https://acc.datanose.nl/#course[77353]/canvasgrading) without uploading any exams.

**Comment by rvankoten** [comment]
Works for me, however it won't check if you have rights for UserAction.GradesEnterExemption
The check was always skipped with this action so I kept it like that.

**Comment by goomens** [comment]
Ahh right, that explains it. I must have tested as someone else last time
