### ISSUE TITLE
Minor layout details

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#23]
- [x] Hide the find and clear buttons if no text has been entered into the search field
- [x] Hide the "show grade calculation" button if there's no grade calculation (i.e. no children)
- [x] On the signing screen, maybe show the catalog number in a smaller font below the course title (along with the date) rather than the current huge font :-)

**Comment by goomens** [comment]
Looks good, but there now seem to be some oddities in the search on (I tested on https://acc.datanose.nl/#course[91463]/canvasgrading):
- Type 'Francis' in the search box and press enter.
- Nothing happens until you click something else, then the filtering applies

Also:
- Delete the typed text from the box
- The buttons disappear but the filter doesn't turn off
- Press enter. The filter turns off once you click another button

**Comment by rvankoten** [comment]
Fixed
