### ISSUE TITLE
Rights issue: fields not editable

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#25]
In https://acc.datanose.nl/#course[80425]/canvasgrading while logged in as admin, I am allowed to enter grades and supervisors, but not titles or exam dates.

**Comment by rvankoten** [comment]
@goomens I think these are locked because of the thesis workflow.
Even for admins it shouldn't make sense to unlock these if they get overwriten right?

If I remeber correctly we can't get the supervisor from the workflow for now.

**Comment by goomens** [comment]
Hmm, makes sense, but maybe we should allow apply the thesis workflow lockout only for students where there is actually data in the thesis workflow?

**Comment by rvankoten** [comment]
But then it may be overwritten later on. Maybe thats not a problem or we need to add a 'manual input' flag again en add reload all buttons.

**Comment by goomens** [comment]
I'll put this on my list of things to discuss with the faculties
