### ISSUE TITLE
Individual fields gone?

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#29]
In https://acc.datanose.nl/#course[95434]/canvasgrading I don't see the title/supervisor/exam date fields, but the course is set to individual. What's going on?

**Comment by rvankoten** [comment]
Nothing wrong with the tool. Course.Type is set to standard so it's shown as standard.
Did not yet check if type is not set correctly according to INOE attribute.

**Comment by goomens** [comment]
Whoops, you're right, somehow I mixed up the courses!
