### ISSUE TITLE
Cookie blocking issues

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#35]
Certain browsers block cross-site cookies aggressively, preventing the tool from loading within Canvas. 

This might not be easy to fix, but can we at least show a warning for the user that they might need to disable the tracking blocking.

Safari in particular does this by default with the 'cross-site tracking' option.

**Comment by rvankoten** [comment]
Not sure if this still works, but cookies in iframes may be allowed by safari if there already is a cookie.

**Comment by rvankoten** [comment]
Added text to main DN startup page
