### ISSUE TITLE
Tooltip for rejected grades

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#36]
When a grade has been rejected (e.g. #pendinggrade/list[96521,81740]), make sure that status is shown in the grade screen with a cross. Add a tooltip showing 'Grade has been rejected by administratie'/'Cijfers is afgewezen door onderwijsadministratie'

**Comment by rvankoten** [comment]
This always had been there already right? Or do you mean something different.
Tooltip text was a bit different.

**Comment by goomens** [comment]
FGw didn't see it while testing but I didn't check 😄 . If it is there we only need to update the text.

**Comment by rvankoten** [comment]
How did FGw test this, could they use the screen to reject grades?

**Comment by goomens** [comment]
No, they can't yet, but I rejected it for them!

**Comment by rvankoten** [comment]
Prabably course 123123010Y and student 12633925. This works, guess they didn't refresh te page or something.
Text is changed.
