### ISSUE TITLE
VU grade processing

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#37]
For grades that come from the VU (CourseYear.ExternalType == VU and/or SignedBy = VUCIJFERS), create classes with section `EXVU` instead of `EXCV`

**Comment by rvankoten** [comment]
Currently it seems to create sections EX01, not EXCV, is this incorrect?

**Comment by goomens** [comment]
Hmm, Ingrid mentioned EXCV, not sure where that came from. EX01 is fine for regular courses
