### ISSUE TITLE
View-only rights

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#41]
Change the permissions so that anyone who can view grades in Canvas can also view grades and calculation settings in the grading tool, in a read-only view. Keep editing permissions as they are now.

**Comment by rvankoten** [comment]
@goomens what about the publish grade rights for view-only users? Nothing is set to hide the button a.t.m.
And what about the other options in the 'calulate grade' dorpdown menu?

**Comment by goomens** [comment]
Hide all options that change grades, and publish grades
