### ISSUE TITLE
Issue with different careers

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#42]
See [DEF1329](https://huva-sis.testersuite.nl/testcycle/45/defect/1329#details). Here students are enrolled for the main course with career 60. Why does it fail to process the grades? Does it pick the wrong career, or is there something wrong in SIS and is it impossible to process them? In the latter case, add a new career mismatch error type

**Comment by goomens** [comment]
In [DEF1333](https://huva-sis.testersuite.nl/testcycle/45/defect/1333) there's another career issue. Is this the same?

**Comment by rvankoten** [comment]
I think this was already fixed a long time ago.
Carreer 60 will always be processed with an overide carreer.
For FNWI we always do override areer anyway.
Other career mismatched for non-FNWI courses will still fail (as intended?)
