### ISSUE TITLE
Delete unenrolled students without grades

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#44]
When loading a grade list, delete any unenrolled students from the list if they have no grades at all (or a NAP)

**Comment by goomens** [comment]
This doesn't seem to work yet for https://acc.datanose.nl/#course[90647]/canvasgrading (I removed all students from the course)

**Comment by rvankoten** [comment]
I don't think the ACC was updated with the current version. I also still see all the students on the course so it may not be syncing correcty wit SIS ACC a.t.m.
Also I made the removal of students a bit conservative, any grades present, submitted or not and also partial grades, will stop the removal.

**Comment by goomens** [comment]
Looks like it does work now! I think it's ok to still remove students if there's only partial grades, as long as no final grade has been entered.
