### ISSUE TITLE
Individual courses

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#5]
Add the fields "Title", "Assessor" and "Examination date" to the Canvas layout for individual courses (i.e. when Course.IsIndividual is set). The fields should appear when the grade row is expanded. Title is a free text field, assessor should be chosen from a list of people using a PersonPicker variant. Title and assessor are (for now?) not required to submit grades, the date is required and should be validated as follows:
- Date should be in the past
- Date needs to within the period for the course
- Date cannot be 31/1 or 31/8 (suggest 30/x in this case)

There are currently no retakes for individual courses so the retake column can be hidden.

**Comment by goomens** [comment]
@rvankoten What field do we write assessor to in SIS? As I recall there is a link-to-person field as well as a free entry field.

**Comment by rvankoten** [comment]
@goomens 
That depends on whether you select a known employee or an external/custom employee in the picker.

The batch task then selects `entry.DailySupervisor`
If it's Employee is NULL or department is 'Extern' it's considered an external.
For internal it selects the `Employee.Person.EmployeeUvAnetID` and for external the `CorrectedEntry.SupervisorString` (which is an email address)

Then the connector sends the INOE request which, if I remember correctly, also has a supervisor field that should not be used.
If this is successfull then it sends either an internal or external attributes requests.
The internal sets the SNS_EMPLID_CNS field and the external the SNS_COUNSELOR field.
