### ISSUE TITLE
Error overview 

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#54]
### Component
Admin interface

### Summary
Create a screen that shows an overview of all errors, showing one row per failed grade so that you don't have to open individual grade lists.

### Requested by
FMG (Angela)

**Comment by ftbloem1** [comment]
Impl coord: wens is nog actueel, maar misschien is het goed om met Gerrit te kijken naar de schermen om te onderzoeken of er een alternatieve manier is.

**Comment by c-wegman** [comment]
Madelon checkt of het actueel is en ander de issue sluiten.
