### ISSUE TITLE
Allow removal of grades

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#57]
### Component
Grade submission, corrections

### Summary
In addition to changing grades, allow corrections that remove an old grade entirely.

### Requested by
FGw (Ingrid), DEF1506

**Comment by goomens** [comment]
Maybe as an admin-only function: allow admins to remove a grade. Carry checks the legal implications.

**Comment by ftbloem1** [comment]
Impleco's: zoeken nog legal implications (sorry was blijven hangen). 
In ieder geval niet opnemen als gebruikers functionaliteit. Als het al een wens wordt dan alleen als admin-only.

**Comment by goomens** [comment]
This has now been implemented for admins with the `CourseDeleteGrades` action. In the submitted grade list view there is a wrench icon which leads to a dialog with a delete link. Deleting will delete the grade from SIS and change the status in DN to "rejected". The grade will still be stored but shown with a red cross.
