### ISSUE TITLE
Update CurriculumTasks.SetOwners

### ISSUE THREAD

**Issue by rvankoten** [UvA-FNWI/GradeTool#65]
Function is broken because some departments don't exist anymore in DB (at least at acc)
Other departments may be missing.
This is needed for the gradetool.

**Comment by goomens** [comment]
Ah, I think the function is good, the acc db is outdated; the subfaculties for FMG aren't in there (CW/PSY/POWL/SW), and PPLE under FdR. If you create them it should work again

**Comment by goomens** [comment]
Subfaculties added in ACC
