### ISSUE TITLE
Read-only grade box issue

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#67]
In https://acc.datanose.nl/#course[98417]/canvasgrading the retake grades are all read-only and empty (because NAPs were removed) and it's impossible to do a correction as well. Either they shouldn't be read-only (because no grade has been entered yet) or it should be possible to do a correction, it seems.

DEF1567

**Comment by goomens** [comment]
There still seems to be a student in that course for whom it is impossible to enter a retake grade.

**Comment by rvankoten** [comment]
Fot this course there is no partial submisson, so when you don't enter a retake, you cant do it later.
Unless we actually want to sort of always enable partial submissions for retakes.

Maybe a correction should still be possible in the current situation (which is not possible a.t.m.)

**Comment by goomens** [comment]
Either the original grade or the correction should be possible, yes :-). Maybe it makes most sense to always allow grades to be entered whenever there are students without grades, with the usual restriction that you must submit all ungraded students at once (so 'partial' means 'you can submit part of the grades' rather than 'you can only submit once')
