### ISSUE TITLE
Fix examdate for INOE lists in DN view

### ISSUE THREAD

**Issue by rvankoten** [UvA-FNWI/GradeTool#72]
Examdate is not shown for each student and is shown (incorrectly) for complete list on top.

Example: https://datanose.nl/#course[100281]/gradeinput/list[103284]

**Comment by goomens** [comment]
When viewing a [submitted list](https://acc.datanose.nl/#course[88644]/gradeinput/list[97842]), there is now both an overall exam date and one per entry. Maybe hide the overall one because it is likely to be confusing?
