### ISSUE TITLE
Fix misallignment of row details and toggle icon moving out of screen

### ISSUE THREAD

**Issue by rvankoten** [UvA-FNWI/GradeTool#73]
### Component
Grade list in Canvas

### Description
When expanding a row, the layout changes and the toggle icon can disappear.

### Steps to reproduce
Expand a row in a grade list, in particular while a correction is open.

**Comment by goomens** [comment]
Minor detail, when expanding rows in https://acc.datanose.nl/#course[88644]/canvasgrading, the last cells is white rather than gray. I assume that's not intended?
