### ISSUE TITLE
Add history dialog for corrections

### ISSUE THREAD

**Issue by rvankoten** [UvA-FNWI/GradeTool#76]
### Component
Grade list view, in Canvas or admin screen

### Summary
Add a dialog that shows the full correction history for a grade, including who submitted what grade and with what reason.

**Comment by goomens** [comment]
Some minor points:
- Can you add the original grade to the list as well when viewing from DN? (and then maybe we need column headers to indicate the type column?)
- Show full name of the submitter rather than UvAnetID
- There are some reports (DEF1776 and DEF1778) that this doesn't work for retakes
