### ISSUE TITLE
Expand individual grade details when entering grade

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#86]
### Component
Grade table for individual course

### Description
Automatically expand the details once a user enters a grade, to make it clear these fields need to be filled out as well.

### Requested by
FGw

**Comment by jvdberge** [comment]
Please also expand the details when row is selected for submission (and a grade and details may already be present). In this way, the examiner will always see what is about to be submitted.

**Comment by goomens** [comment]
Current implementation: whenever a grade is changed and one or more individual fields still need to be entered for that grade, the row is automatically expanded.

**Comment by goomens** [comment]
Always expand when row is selected.
